---
AWSTemplateFormatVersion: '2010-09-09'
Description: A Lambda function for scheduling later Lambda function executions.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Configuration
      Parameters:
      - MetricAlarmEmailAddress
      - LogRetentionDays
    ParameterLabels:
      LogRetentionDays:
        default: Log Retention (days)
      MetricAlarmEmailAddress:
        default: Alarm E-mail Address
Parameters:
  LogRetentionDays:
    Type: String
    Default: '14'
    AllowedValues:
    - ''
    - '1'
    - '3'
    - '5'
    - '7'
    - '14'
    - '30'
    - '60'
    - '90'
    - '120'
    - '150'
    - '180'
    - '365'
    - '400'
    - '545'
    - '731'
    - '1827'
    - '3653'
  MetricAlarmEmailAddress:
    Type: String
    Description: In case of errors. Leave blank to disable.
    Default: ''
Mappings:
  StaticVariables:
    Main:
      StageName: v1
Conditions:
  IncludeMetricAlarmsCondition:
    Fn::Not:
    - Fn::Equals:
      - Ref: MetricAlarmEmailAddress
      - ''
Resources:
  
  #
  #   Invocation Queuer
  #   
  #   This is the function that receives requests to have Lambda functions 
  #   executed at a later time.
  #
  
  InvocationQueuerFunction:
    Type: AWS::Lambda::Function
    Metadata:
      SharedBucket:
        Ref: SharedBucket
    Properties:
      Description: Queues up Lambda function invocations for later execution.
      Handler: index.lambda_handler
      MemorySize: 128
      Role:
        Fn::GetAtt:
        - InvocationQueuerFunctionRole
        - Arn
      Code:
        S3Bucket:
          Ref: SharedBucket
        S3Key: lambda/InvocationQueuerFunction.zip
      Runtime: python2.7
      Timeout: '300'
  InvocationQueuerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  InvocationQueuerFunctionRoleActions:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: InvocationQueuerFunctionRoleActions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource:
            Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${InvocationQueuerFunction}:log-stream:*
        - Effect: Allow
          Action:
          - s3:PutObject
          Resource:
            Fn::Sub: arn:aws:s3:::${SharedBucket}/queued/*
        - Effect: Allow
          Action:
          - iam:GetRolePolicy
          Resource:
            Fn::Sub: arn:aws:iam::${AWS::AccountId}:role/${InvocationQueuerFunctionRole}
        - Effect: Allow
          Action:
          - cloudformation:DescribeStackResource
          Resource:
            Fn::Sub: ${AWS::StackId}
      Roles:
      - Ref: InvocationQueuerFunctionRole
  InvocationQueuerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${InvocationQueuerFunction}
      RetentionInDays:
        Ref: LogRetentionDays
  
  #
  #   Stack Cleanup
  #   
  #   This function performs basic setup and cleanup functionality when the 
  #   stack is deleted.
  #   
  #   On delete:
  #     - Clears out S3 bucket
  #
  
  StackCleanupFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Queues up Lambda function invocations for later execution.
      Handler: index.lambda_handler
      MemorySize: 1024
      Role:
        Fn::GetAtt:
        - StackCleanupFunctionRole
        - Arn
      Code:
        ZipFile: |-
          from __future__ import print_function

          import json
          import boto3
          import cfnresponse

          class LambdaHandler(object):
              
              def __init__(self, context):
                  pass
  
              def handle_event(self, event, context):
                  print("Event: {}".format(json.dumps(event)))
        
                  request_type = event.get("RequestType")
        
                  if request_type == "Delete":
                      
                      # 
                      # Make sure the STACK is being deleted (and not just this resource).
                      # 
                      # This avoids someone who's just tinkering with the template from wiping out 
                      # the whole bucket.
                      # 
                      if boto3.resource("cloudformation").Stack(event["StackId"]).stack_status == "DELETE_IN_PROGRESS":
                          self.handle_cleanup_event(event, context)
        
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {}, None)
        
                  return {}
    
              def handle_cleanup_event(self, event, context):
        
                  s3_client = boto3.client("s3")
                  s3_bucket_name = event["ResourceProperties"]["SharedBucket"]
        
                  paginator = s3_client.get_paginator("list_objects_v2")
        
                  response_iterator = paginator.paginate(
                      Bucket = s3_bucket_name
                  )
        
                  for each_list_response in response_iterator:
                    keys_to_delete = []
          
                    for each_item in each_list_response.get("Contents", []):
                        keys_to_delete.append(each_item["Key"])
          
                    if len(keys_to_delete) == 0:
                        print("Last request for objects in {} returned none.".format(
                            s3_bucket_name
                        ))
                        break
          
                    print("Deleting {} object(s) from {}.".format(
                        len(keys_to_delete),
                        s3_bucket_name
                    ))
          
                    s3_client.delete_objects(
                        Bucket = s3_bucket_name,
                        Delete = {
                            "Objects": list({"Key": x} for x in keys_to_delete)
                        }
                    )
          
                    print("Object(s) deleted.")

          handler_object = None
          def lambda_handler(event, context):
              global handler_object
    
              if handler_object is None:
                  handler_object = LambdaHandler(context)
    
              return handler_object.handle_event(event, context)
              
      Runtime: python2.7
      Timeout: '300'
  StackCleanupFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
  StackCleanupFunctionRoleActions:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: StackCleanupFunctionRoleActions
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action:
          - logs:CreateLogStream
          - logs:PutLogEvents
          Resource:
            Fn::Sub: arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/${StackCleanupFunction}:log-stream:*
        - Effect: Allow
          Action:
          - cloudformation:DescribeStacks
          Resource:
            Fn::Sub: ${AWS::StackId}
        - Effect: Allow
          Action:
          - s3:DeleteObject
          Resource:
            Fn::Sub: arn:aws:s3:::${SharedBucket}/*
        - Effect: Allow
          Action:
          - s3:ListBucket
          Resource:
            Fn::Sub: arn:aws:s3:::${SharedBucket}
      Roles:
      - Ref: StackCleanupFunctionRole
  StackCleanupFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StackCleanupFunction}
      RetentionInDays:
        Ref: LogRetentionDays
  StackCleanupInvocation:
    Type: Custom::StackCleanupInvocation
    Properties:
      ServiceToken:
        Fn::GetAtt:
        - StackCleanupFunction
        - Arn
      SharedBucket:
        Ref: SharedBucket
    DependsOn:
    - StackCleanupFunctionLogGroup
    - StackCleanupFunctionRoleActions
  
  SharedBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
        
Outputs:
  SharedBucket:
    Value:
      Ref: SharedBucket
