---
AWSTemplateFormatVersion: '2010-09-09'
Description: Initial Deployment - A Lambda function for scheduling later Lambda function executions.
Resources:
  
  SharedBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
        
Outputs:
  SharedBucket:
    Value:
      Ref: SharedBucket
